version: "3.9"
name: "BeeBnB"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
