import { Booking, BookingStatus } from "../types/booking";

export const mockBookings: Booking[] = [
  {
    id: "1",
    guestName: "John Doe",
    checkIn: "2023-12-01",
    checkOut: "2023-12-05",
    guests: 2,
    status: BookingStatus.Confirmed,
    totalPrice: 750,
    amenities: [
      "Free Wi-Fi",
      "Breakfast Included",
      "Mountain View",
      "Private Bathroom",
    ],
    bnbName: "Cozy Mountain Retreat",
    bnbAddress: "123 Pine Lane, Mountain Town, MT 12345",
    bnbPhone: "+1 (555) 123-4567",
    bnbEmail: "info@cozymountainretreat.com",
  },
  {
    id: "2",
    guestName: "Jane Smith",
    checkIn: "2023-12-10",
    checkOut: "2023-12-15",
    guests: 1,
    status: BookingStatus.Pending,
    totalPrice: 500,
    amenities: ["Free Wi-Fi", "Breakfast Included", "City View", "Gym Access"],
    bnbName: "Urban Stay Downtown",
    bnbAddress: "456 Main Street, Metro City, MC 67890",
    bnbPhone: "+1 (555) 987-6543",
    bnbEmail: "contact@urbanstay.com",
  },
  {
    id: "3",
    guestName: "Robert Brown",
    checkIn: "2023-12-20",
    checkOut: "2023-12-25",
    guests: 4,
    status: BookingStatus.Confirmed,
    totalPrice: 1200,
    amenities: ["Free Wi-Fi", "Beach Access", "Pool Access", "Private Balcony"],
    bnbName: "Seaside Escape",
    bnbAddress: "789 Ocean Drive, Coastline, CL 23456",
    bnbPhone: "+1 (555) 234-5678",
    bnbEmail: "reservations@seasideescape.com",
  },
  {
    id: "4",
    guestName: "Emily Davis",
    checkIn: "2023-12-05",
    checkOut: "2023-12-08",
    guests: 3,
    status: BookingStatus.Cancelled,
    totalPrice: 650,
    amenities: ["Free Wi-Fi", "Pet Friendly", "Lake View", "Fireplace"],
    bnbName: "Lakeside Cabin Retreat",
    bnbAddress: "321 Lake Road, Tranquil Shores, TS 34567",
    bnbPhone: "+1 (555) 345-6789",
    bnbEmail: "bookings@lakesidecabinretreat.com",
  },
  {
    id: "5",
    guestName: "Michael Green",
    checkIn: "2023-12-28",
    checkOut: "2024-01-02",
    guests: 6,
    status: BookingStatus.Confirmed,
    totalPrice: 1800,
    amenities: ["Free Wi-Fi", "Hot Tub", "Game Room", "Mountain View"],
    bnbName: "Luxury Chalet",
    bnbAddress: "789 Snowy Ridge, Alpine Heights, AH 45678",
    bnbPhone: "+1 (555) 456-7890",
    bnbEmail: "luxury@alpinechalet.com",
  },
  {
    id: "6",
    guestName: "Sophia Taylor",
    checkIn: "2024-01-10",
    checkOut: "2024-01-15",
    guests: 2,
    status: BookingStatus.Pending,
    totalPrice: 900,
    amenities: [
      "Free Wi-Fi",
      "Spa Access",
      "Garden View",
      "Breakfast Included",
    ],
    bnbName: "Tranquility Garden Inn",
    bnbAddress: "654 Blossom Way, Greenfield, GF 56789",
    bnbPhone: "+1 (555) 678-1234",
    bnbEmail: "relax@tranquilitygarden.com",
  },
];
